"""Initial schema

Revision ID: 4437f5f2154e
Revises: 
Create Date: 2026-07-03 20:03:37.897607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4437f5f2154e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'tag_id', name='uq_transaction_tag')
    )
    with op.batch_alter_table('transaction_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_tags_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_account_identifier')
        batch_op.drop_index('ix_accounts_bank_name')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_gmail_id')
        batch_op.create_index(batch_op.f('ix_transactions_gmail_id'), ['gmail_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_parent_transaction_id'), ['parent_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_parent_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))
        batch_op.drop_index(batch_op.f('ix_transactions_gmail_id'))
        batch_op.create_index('ix_transactions_gmail_id', ['gmail_id'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_bank_name', ['bank_name'], unique=False)
        batch_op.create_index('ix_accounts_account_identifier', ['account_identifier'], unique=False)

    with op.batch_alter_table('transaction_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_tags_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_tags_tag_id'))

    op.drop_table('transaction_tags')
    # ### end Alembic commands ###
